version: '3.5'

services:
  client:
    image: node:17-alpine
    volumes:
      - ./client/:/app:cached
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    expose:
      - 3000

  server:
    image: node:17-alpine
    volumes:
      - ./server/:/app:cached
    working_dir: /app
    ports:
      - 3001:3001
    command: npm start
    expose:
      - 3001

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=simple-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
